/*
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_SENSOR_SCD4x_H_
#define ZEPHYR_DRIVERS_SENSOR_SCD4x_H_

#define SCD4x_CMD_START_PERIODIC_MEAS_MSB (uint8_t)0x21
#define SCD4x_CMD_START_PERIODIC_MEAS_LSB (uint8_t)0xB1

#define SCD4x_CMD_READ_MEAS_MSB (uint8_t)0xEC
#define SCD4x_CMD_READ_MEAS_LSB (uint8_t)0x05

#define SCD4x_CMD_STOP_PERIODIC_MEAS_MSB (uint8_t)0x3F
#define SCD4x_CMD_STOP_PERIODIC_MEAS_LSB (uint8_t)0x86

#define SCD4x_CMD_SET_TEMPERATURE_OFFSET_MSB (uint8_t)0x24
#define SCD4x_CMD_SET_TEMPERATURE_OFFSET_LSB (uint8_t)0x1D

#define SCD4x_CMD_GET_TEMPERATURE_OFFSET_MSB (uint8_t)0x23
#define SCD4x_CMD_GET_TEMPERATURE_OFFSET_LSB (uint8_t)0x18

#define SCD4x_CMD_SET_TEMPERATURE_ALTITUDE_MSB (uint8_t)0x24
#define SCD4x_CMD_SET_TEMPERATURE_ALTITUDE_LSB (uint8_t)0x27

#define SCD4x_CMD_GET_TEMPERATURE_ALTITUDE_MSB (uint8_t)0x23
#define SCD4x_CMD_GET_TEMPERATURE_ALTITUDE_LSB (uint8_t)0x22

#define SCD4x_CMD_SET_AMBIENT_PRESSURE_MSB (uint8_t)0xE0
#define SCD4x_CMD_SET_AMBIENT_PRESSURE_LSB (uint8_t)0x00

#define SCD4x_CMD_PERFORM_FORCED_RECAL_MSB (uint8_t)0x36
#define SCD4x_CMD_PERFORM_FORCED_RECAL_LSB (uint8_t)0x2F

#define SCD4x_CMD_SET_AUTOMATIC_SELF_CALIBRATION_ENABLED_MSB (uint8_t)0x24
#define SCD4x_CMD_SET_AUTOMATIC_SELF_CALIBRATION_ENABLED_LSB (uint8_t)0x16

#define SCD4x_CMD_GET_AUTOMATIC_SELF_CALIBRATION_ENABLED_MSB (uint8_t)0x23
#define SCD4x_CMD_GET_AUTOMATIC_SELF_CALIBRATION_ENABLED_LSB (uint8_t)0x13

#define SCD4x_CMD_START_LOW_POWER_PERIODIC_MEAS_MSB (uint8_t)0x21
#define SCD4x_CMD_START_LOW_POWER_PERIODIC_MEAS_LSB (uint8_t)0xAC

#define SCD4x_CMD_GET_DATA_READY_STATUS_MSB (uint8_t)0xE4
#define SCD4x_CMD_GET_DATA_READY_STATUS_LSB (uint8_t)0xB8

#define SCD4x_CMD_PERSIST_SETTINGS_MSB (uint8_t)0x36
#define SCD4x_CMD_PERSIST_SETTINGS_LSB (uint8_t)0x15

#define SCD4x_CMD_GET_SERIAL_NUMBER_MSB (uint8_t)0x36
#define SCD4x_CMD_GET_SERIAL_NUMBER_LSB (uint8_t)0x82

#define SCD4x_CMD_PERFORM_SELF_TEST_MSB (uint8_t)0x36
#define SCD4x_CMD_PERFORM_SELF_TEST_LSB (uint8_t)0x39

#define SCD4x_CMD_PERFORM_FACTORY_RESET_MSB (uint8_t)0x36
#define SCD4x_CMD_PERFORM_FACTORY_RESET_LSB (uint8_t)0x32

#define SCD4x_CMD_REINIT_MSB (uint8_t)0x36
#define SCD4x_CMD_REINIT_LSB (uint8_t)0x46

#define SCD4x_CMD_MEASURE_SINGLE_SHOT_MSB (uint8_t)0x21
#define SCD4x_CMD_MEASURE_SINGLE_SHOT_LSB (uint8_t)0x9D

#define SCD4x_CMD_MEASURE_SINGLE_SHOT_RHT_ONLY_MSB (uint8_t)0x21
#define SCD4x_CMD_MEASURE_SINGLE_SHOT_RHT_ONLY_LSB (uint8_t)0x96

#define SCD4x_CMD_LEN 2

#endif /* ZEPHYR_DRIVERS_SENSOR_SCD4x_H_ */
